// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "calsync-mirror",
    platforms: [.macOS(.v14)],
    targets: [
        // The logic worth testing — ICS parsing, the marker, the guard,
        // reconciliation — with no EventKit and no network in it.
        .target(name: "CalsyncMirrorCore"),
        // EventKit, kept out of Core so the decision layer stays testable
        // without a calendar. Shared by the CLI and the menu bar app, which are
        // two front ends over one planner rather than two implementations.
        .target(
            name: "CalsyncMirrorEventKit",
            dependencies: ["CalsyncMirrorCore"]
        ),
        // EventKit and URLSession live behind protocols the core declares, so
        // the executable is the only thing that touches either.
        .executableTarget(
            name: "calsync-mirror",
            dependencies: ["CalsyncMirrorCore", "CalsyncMirrorEventKit"]
        ),
        .executableTarget(
            name: "CalsyncMirrorMenu",
            dependencies: ["CalsyncMirrorCore", "CalsyncMirrorEventKit"]
        ),
        .testTarget(
            name: "CalsyncMirrorCoreTests",
            dependencies: ["CalsyncMirrorCore"],
            // games.ics is generated by calsync's own `to_ics`, so the parser
            // is held against real output rather than against a guess at it.
            resources: [.copy("Fixtures")]
        ),
    ]
)
